### ISSUE TITLE
allow viewing file:/// links

### ISSUE THREAD

**Issue by ekg** [pRizz/SVG-Navigator---Chrome-Extension#30]
Right now SVG-Navigator is only enabled when opening http:// links. Is there a simple way to also enable it when opening local files? I view a lot of SVGs on my own laptop and this would be simpler than running a webserver to view them.

**Comment by pRizz** [comment]
You can access file URLs by going to Chrome's extension settings, and checking "Allow access to file URLs"

**Comment by ekg** [comment]
Awesome, thanks.

**Comment by pRizz** [comment]
You've very welcome!
