### ISSUE TITLE
Suggestion: non-white background-color for white SVG

### ISSUE THREAD

**Issue by jossmac** [pRizz/SVG-Navigator---Chrome-Extension#36]
Hi, thank you for writing this OSS extension!

I was just trying to view an all-white SVG and had to update the body's `background-color` manually to be able to see it.

The color wouldn't have to be terribly dark, just enough to provide contrast; something like `#eee`. 

The feature could be opt-in?

**Comment by pRizz** [comment]
Hi @jossmac, thanks for the appreciation!

Your idea makes sense. I think I can provide a way to change the background color in the options of the app. I'll see what I can do.

**Comment by pRizz** [comment]
Implemented in v2.4.1
